# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pairs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpairs.proto\x12\x05pairs\"4\n\x0fRegisterRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x10\n\x08keysList\x18\x02 \x03(\x05\"%\n\x10RegisterResponse\x12\x11\n\tkeysCount\x18\x01 \x01(\x05\",\n\x17ServerTerminateResponse\x12\x11\n\tkeysCount\x18\x01 \x01(\x05\"\x12\n\x10TerminateRequest\"\x19\n\nMapRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\x1e\n\x0bMapResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"+\n\rInsertRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\" \n\x0eInsertResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1c\n\rSearchRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\x1f\n\x0eSearchResponse\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x0f\x41\x63tivateRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x10\x41\x63tivateResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"#\n\x11TerminateResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xff\x01\n\nOperations\x12\x37\n\x06Insert\x12\x14.pairs.InsertRequest\x1a\x15.pairs.InsertResponse\"\x00\x12\x37\n\x06Search\x12\x14.pairs.SearchRequest\x1a\x15.pairs.SearchResponse\"\x00\x12=\n\x08\x41\x63tivate\x12\x16.pairs.ActivateRequest\x1a\x17.pairs.ActivateResponse\"\x00\x12@\n\tTerminate\x12\x17.pairs.TerminateRequest\x1a\x18.pairs.TerminateResponse\"\x00\x32\xd0\x01\n\x11\x43\x65ntralOperations\x12=\n\x08Register\x12\x16.pairs.RegisterRequest\x1a\x17.pairs.RegisterResponse\"\x00\x12.\n\x03Map\x12\x11.pairs.MapRequest\x1a\x12.pairs.MapResponse\"\x00\x12L\n\x0fServerTerminate\x12\x17.pairs.TerminateRequest\x1a\x1e.pairs.ServerTerminateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pairs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=22
  _globals['_REGISTERREQUEST']._serialized_end=74
  _globals['_REGISTERRESPONSE']._serialized_start=76
  _globals['_REGISTERRESPONSE']._serialized_end=113
  _globals['_SERVERTERMINATERESPONSE']._serialized_start=115
  _globals['_SERVERTERMINATERESPONSE']._serialized_end=159
  _globals['_TERMINATEREQUEST']._serialized_start=161
  _globals['_TERMINATEREQUEST']._serialized_end=179
  _globals['_MAPREQUEST']._serialized_start=181
  _globals['_MAPREQUEST']._serialized_end=206
  _globals['_MAPRESPONSE']._serialized_start=208
  _globals['_MAPRESPONSE']._serialized_end=238
  _globals['_INSERTREQUEST']._serialized_start=240
  _globals['_INSERTREQUEST']._serialized_end=283
  _globals['_INSERTRESPONSE']._serialized_start=285
  _globals['_INSERTRESPONSE']._serialized_end=317
  _globals['_SEARCHREQUEST']._serialized_start=319
  _globals['_SEARCHREQUEST']._serialized_end=347
  _globals['_SEARCHRESPONSE']._serialized_start=349
  _globals['_SEARCHRESPONSE']._serialized_end=380
  _globals['_ACTIVATEREQUEST']._serialized_start=382
  _globals['_ACTIVATEREQUEST']._serialized_end=411
  _globals['_ACTIVATERESPONSE']._serialized_start=413
  _globals['_ACTIVATERESPONSE']._serialized_end=446
  _globals['_TERMINATERESPONSE']._serialized_start=448
  _globals['_TERMINATERESPONSE']._serialized_end=483
  _globals['_OPERATIONS']._serialized_start=486
  _globals['_OPERATIONS']._serialized_end=741
  _globals['_CENTRALOPERATIONS']._serialized_start=744
  _globals['_CENTRALOPERATIONS']._serialized_end=952
# @@protoc_insertion_point(module_scope)
